language: node_js
node_js:
  - 8
script: 'true'
install:
  - npm install -g firebase-tools
deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master
# after_success:
#   - cd functions
#   - npm install
#   - cd ..
#   - firebase deploy --project tigerhacks --token $FIREBASE_TOKEN
