language: node_js
node_js:
- 8
deploy:
  provider: firebase
  token:
    secure: ZW2K+/aSrS2vWkQU4f3HnlYEsudHrKgpiEX6LMTMphzGgX8xqgLD0zdXoejbWBUxkWSBekO2w0BqmJJjtwjr6+XWz9XkEny0gCTV0uoPmUh+dnPLGicUdwq9rJ3sn9qTobkLDvXOOMDavIVK84HHC6/zAlFB4I2jbo8FDzpiulgqwubmnYItiKqW8c7dvuWzmjGREvH1MZsFW7fKKiPiQ2s7gFsA+XiIb/2Np28fpNM5tJ/np4dDTEEOK/bOwsWVYGbF3ZZLu3bH2plticmTY5TQFPd2Pc4ETAY90UlOaGuU9r220rsZJDH3YvRiKhBDzOoyhMkbVNBMp3ZBAMKTnxJaec/YyDSgNf52HVZxmvTE+PuwvBhm3jgmF69tftkN1+e7bvOsG2vPMI8mSvuK6vweJbhYW4zlWFwkLacEKvmXJ9HD0sdkPw40UQ7j2wN6NFkN1+SV1E3mnH0vznOU0JKHOp2J4yQWws5xfvt8UTEDGgNmtUoBpVB/NrqYH6xnb0ohEidsNqk3q+ZxmdYf9h6eyRn8X2CC7JTB128ei6NB5ZJ1HId97NqGMqQLDVQ35TxiGsNq0X7PN/3vQByFkhDVkGolc59UcjAmJmLOgJL/ziKNxC5FBhwa2LSu1GT39QO7Gxrvly0ijDhmMHbZLHK/9wC6aA0Uzu1V+ikB08M=
